# User config
author: "Prakash Prasad"
tagline: "Projects"
description: "I've worked on many projects. Here's a showcase of some..."
keywords: "Projects, Code, Game, Techonology, Rendering"
email: "prakash@prakashprasad.com"
resume: "https://resume.prakashprasad.com/"
blog: "https://shader.works/"
linkedin: "https://www.linkedin.com/in/prakashprasad/"
twitter: "https://twitter.com/indusninja/"
github: "https://github.com/indusninja/"
youtube: "https://www.youtube.com/user/prakashf1/"
url: "http://prakashprasad.com/"
# some of these links should depend on where the request if coming from
# for example: 
# if projects.shader.works: then link should be resume.shader.works
# if prakashprasad.com: then link should be resume.prakashprasad.com

# Site config
port: 4000
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed

# plugins
plugins:
  - jekyll-youtube
  - jekyll-analytics
  - jekyll-email-protect
  - jekyll-sitemap

# google analytics information
jekyll_analytics:
  GoogleAnalytics:
    id: UA-27962903-2
    anonymizeIp: true