# User config
author: "Prakash Prasad"
tagline: "Projects"
description: "I've worked on many projects. Here's a showcase of some..."
keywords: "Projects, Code, Game, Techonology, Rendering"
email: "prakash@prakashprasad.com"
linkedin: "https://www.linkedin.com/in/prakashprasad/"
twitter: "https://twitter.com/indusninja/"
github: "https://github.com/indusninja/"
youtube: "https://www.youtube.com/user/prakashf1/"
url: "http://projects.shader.works/"

# Site config
port: 5000
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed

# plugins
plugins:
  - jekyll-youtube
  - jekyll-analytics
  - jekyll-email-protect
  - jekyll-sitemap

# google analytics information
jekyll_analytics:
  GoogleAnalytics:
    id: UA-27962903-2
    anonymizeIp: true